"use client"

import React from "react"
import { Eye } from "lucide-react"
import { Button } from "@/components/ui/button"
import { SecurityPreferences } from "./types"

interface PrivacySectionProps {
  preferences: SecurityPreferences;
  onChange: (key: keyof SecurityPreferences, value: boolean) => void;
}

export function PrivacySection({ preferences, onChange }: PrivacySectionProps) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-foreground mb-1 flex items-center gap-2">
          <Eye className="h-5 w-5 text-primary" />
          Privacy & Data
        </h2>
        <p className="text-sm text-muted mb-6">Manage how your security and identity data is handled.</p>
      </div>

      <div className="bg-surface border border-border/50 rounded-xl overflow-hidden divide-y divide-border/50">
        
        {/* Audio Processing */}
        <div className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-base font-bold text-foreground mb-1">Audio Processing</h3>
              <p className="text-sm text-muted mb-3 max-w-lg">
                Control how voice recordings and protected-call audio are handled.
              </p>
              <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-surface-elevated border border-border/50 text-xs font-medium text-muted">
                Status: Processed for analysis
              </div>
            </div>
          </div>
        </div>

        {/* Voice Identity */}
        <div className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-base font-bold text-foreground mb-1">Voice Identity</h3>
              <p className="text-sm text-muted mb-3 max-w-lg">
                Manage optional trusted voice identities.
              </p>
            </div>
            <div className="shrink-0">
              <Button variant="outline" onClick={() => window.location.href = "/identity"}>
                Manage Identities
              </Button>
            </div>
          </div>
        </div>

        {/* Security History */}
        <div className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-base font-bold text-foreground mb-1">Security History</h3>
              <p className="text-sm text-muted mb-3 max-w-lg">
                Review security activity generated by VoxShield.
              </p>
            </div>
            <div className="shrink-0">
              <Button variant="outline" onClick={() => window.location.href = "/history"}>
                View History
              </Button>
            </div>
          </div>
        </div>

        {/* Data Minimization */}
        <div className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-base font-bold text-foreground mb-1">Data Minimization</h3>
              <p className="text-sm text-muted mb-3 max-w-lg">
                VoxShield should retain only information needed for security decisions and auditability.
              </p>
              <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-success/10 text-success border border-success/20 text-xs font-medium">
                Status: Enabled
              </div>
            </div>
          </div>
        </div>

      </div>

      <div className="bg-surface-elevated/50 p-5 rounded-lg border border-border/50 mt-6">
        <h4 className="text-sm font-semibold text-foreground mb-2">VoxShield Privacy Principles</h4>
        <ul className="text-sm text-muted space-y-1 list-disc pl-4">
          <li>Voice authenticity detection does not require voice registration.</li>
          <li>Trusted voice identity is strictly optional.</li>
          <li>Raw voice should not be stored unnecessarily.</li>
          <li>We do not create a universal voice database.</li>
          <li>Raw biometric data does not belong on the blockchain.</li>
        </ul>
      </div>

    </div>
  )
}
